Repository beyond-sw-camp/be12-2nd-Matfia-Eatzzy, pull requests merged in 2024-12, with the labels that each got.

#5 [Docs] Readme 수정
  README.md
  public/bibim.png
  public/burger.png
  public/icecream.png
  public/logo.png
  public/ramen.png
  public/sushi.png
  public/tteok.png
Labels: 📜Docs

#6 [Docs] logo 수정
  public/logo.png
Labels: 📜Docs

#7 [feature] 점주 마이페이지 수정
  package-lock.json
  package.json
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/ProductOrder.vue
Labels: ✨Feature

#8 [PRODUCT_011] 장바구니 전체 선택 전체 선택 해제 기능
  README.md
  package-lock.json
  package.json
  src/pages/cart/CartCard.vue
  src/pages/cart/Carts.vue
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/ProductOrder.vue
Labels: ✨Feature

#11 [feature] 리뷰작성 페이지 수정
  src/pages/mypage/client/CreateReview.vue
  src/stores/useReviewStore.js
Labels: ✨Feature

#12 장바구니 모달
  src/pages/cart/CartModal.vue
  src/pages/common/Main.vue
  src/pages/product/components/Product.vue
  src/stores/useCartStore.js
Labels: ✨Feature

#13 [FIX] cart-card
  src/pages/cart/CartCard.vue
Labels: 🔧Fix

#18 점주 마이페이지 스타일링, mock server 주소 변경
  README.md
  public/image/bibim.png
  public/image/burger.png
  public/image/icecream.png
  public/image/logo.png
  public/image/ramen.png
  public/image/sushi.png
  public/image/tteok.png
  src/pages/mypage/seller/DeliveryRegister.vue
  src/pages/mypage/seller/ProductEdit.vue
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/ProductModify.vue
  src/pages/mypage/seller/ProductRegister.vue
  src/pages/mypage/seller/Seller.vue
  src/pages/mypage/seller/ShippingRegister.vue
  src/pages/mypage/seller/components/SellerMenu.vue
  src/router/index.js
  src/stores/useCategoryStore.js
  src/stores/useOrderStore.js
  src/stores/useReservationStore.js
  src/stores/useReviewStore.js
  src/stores/useStoresStore.js
  vite.config.js
Labels: 📦Rename, 🎨Style

#20 [Chore] mock server 변경
  vite.config.js
Labels: 📏Chore

#23 장바구니 오류 및 주문 페이지 연결
  src/assets/cart/cart.css
  src/assets/products/products.css
  src/pages/cart/CartCard.vue
  src/pages/cart/Carts.vue
  src/pages/common/components/Header.vue
  src/pages/order/Order.vue
  src/pages/order/components/OrderCard.vue
  src/pages/product/Products.vue
  src/router/index.js
  src/stores/useCartStore.js
Labels: 🔧Fix, ✨Feature

#24 [feature] 점주 사이드바 수정
  src/pages/mypage/seller/components/SellerMenu.vue
  src/stores/useProductsStore.js
  vite.config.js
Labels: ✨Feature

#29 점주 상품 조회 스타일링, 상품 수정 구현
  src/pages/mypage/client/ClientOrderDetail.vue
  src/pages/mypage/client/components/ProductItem.vue
  src/pages/mypage/seller/ProductEdit.vue
  src/pages/mypage/seller/ProductList.vue
  src/stores/useProductsStore.js
  src/utils/formatPrice.js
Labels: ✨Feature, 🎨Style

#33 상품 상세 페이지 소개 리뷰 추가
  src/pages/cart/Carts.vue
  src/pages/product/components/Product.vue
  src/pages/product/components/ProductDescription.vue
  src/pages/product/components/ProductDetail.vue
  src/pages/product/components/ProductReviewList.vue
  src/router/index.js
  src/stores/useProductsStore.js
Labels: ✨Feature

#34 [Style] 점주 주문내역 스타일링
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/ProductOrder.vue
Labels: 🎨Style

#36 [Style] 점주 마이페이지 스타일링 (배송 등록, 상품 주문)
  src/pages/mypage/components/OrderDetail.vue
  src/pages/mypage/seller/DeliveryRegister.vue
  src/pages/mypage/seller/OrderDetails.vue
  src/pages/mypage/seller/ProductEdit.vue
  src/pages/mypage/seller/ProductOrder.vue
  src/pages/mypage/seller/Seller.vue
  src/pages/mypage/seller/components/SellerMenu.vue
  src/router/index.js
Labels: 🎨Style

#41 [Style] 스타일링
  src/pages/mypage/components/MyInfo.vue
  src/pages/mypage/components/OrderDetail.vue
  src/pages/mypage/seller/ProductList.vue
  src/pages/mypage/seller/Seller.vue
  src/pages/mypage/seller/SellerInsertStore.vue
  src/pages/mypage/seller/SellerStoreItem.vue
  src/pages/mypage/seller/SellerStores.vue
  src/pages/mypage/seller/components/SellerMenu.vue
  src/pages/mypage/seller/components/SellerStoreCard.vue
  src/router/index.js
Labels: 🎨Style
