Repository beyond-sw-camp/be12-2nd-Matfia-Eatzzy, pull requests merged in 2025-01, with the labels that each got.

#42 장바구니 기능 재작성
  src/pages/cart/CartCard.vue
  src/pages/cart/Carts.vue
  src/stores/useCartStore.js
Labels: 🔧Fix, ✨Feature

#43 [Style] 점주 식당, 메뉴 스타일링
  src/pages/mypage/seller/SellerMenuList.vue
  src/pages/mypage/seller/components/SellerMenuCard.vue
  src/pages/mypage/seller/components/SellerStoreCard.vue
  src/router/index.js
Labels: 🎨Style

#44 스타일링
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/pages/mypage/seller/SellerEditMenu.vue
  src/pages/mypage/seller/SellerInsertStore.vue
  src/pages/mypage/seller/SellerMenuList.vue
  src/pages/mypage/seller/SellerModifyMenu.vue
  src/pages/mypage/seller/SellerModifyStore.vue
  src/pages/mypage/seller/SellerReservationCard.vue
  src/pages/mypage/seller/components/SellerMenuCard.vue
  src/pages/mypage/seller/components/SellerStoreCard.vue
  src/router/index.js
  src/stores/useMenuStore.js
Labels: 🎨Style

#48 회원가입 클릭 이벤트 추가, 리드미 수정
  README.md
  public/gif/회원가입.gif
  src/pages/user/JoinForm.vue
Labels: 📜Docs, ✨Feature

#50 [Featrue] 장바구니 및 상품 상세페이지에 주문 기능 추가
  src/pages/cart/Carts.vue
Labels: ✨Feature

#52 [DOCS] 리드미 수정
  README.md
  public/gif/내 상품 등록.gif
  public/gif/등록한 상품 조회.gif
  public/gif/배송등록.gif
  public/gif/상품 삭제.gif
  public/gif/상품 수정.gif
  public/gif/식당삭제.gif
  public/gif/식당수정.gif
  public/gif/주문내역확인.gif
Labels: 📜Docs

#53 [Chore] api 경로 수정
  src/stores/useStoresStore.js
Labels: 📏Chore
